### ISSUE TITLE
MeMin produces non-deterministic Mealy machine

### ISSUE THREAD

**Issue by meyerphi** [andreas-abel/MeMin#1]
When running MeMin (built from source) on [input.txt](https://github.com/andreas-abel/MeMin/files/3198770/input.txt), the resulting Mealy machine [result.txt](https://github.com/andreas-abel/MeMin/files/3198772/result.txt) contains, for the same state and input, several transitions to different successor states, which should not happen according to the definition of an incompletely specified Mealy machine from the paper. For example, two of the conflicting transitions are:
```
111 S1 S2 0
11- S1 S0 -
```

**Comment by andreas-abel** [comment]
Your input file has multiple transitions for, e.g., the input 111 from state S0

```
--1 S0 S6 0
-1- S0 S6 0
1-- S0 S6 0
```
This is not supported. The inputs must be disjoint. You could change this example to 
```
--1 S0 S6 0
-10 S0 S6 0
100 S0 S6 0
```

**Comment by meyerphi** [comment]
Okay, thank you. I thought as long as the output is uniquely defined (e.g. `S6 0` in this example), it would be sufficient to give a combination of the minterms leading to that output, as the machine is still deterministic.
